### PR TITLE
update electronicbabble to use FP, add DS hours

### PR DESCRIPTION
**Pull request by rorpage**
* Update electronicbabble.js to use FastPass for Live365 data
* Add Disney Springs hours

### CODE REVIEW

**Comment by rorpage** [comment]
Closes #3 and #4

**Comment by mvbattista** [comment]
LGTM, has it been tested?

**Comment by rorpage** [comment]
Yep, going to add my test page for kicks

**Comment by rorpage** [comment]
image

**Comment by mvbattista** [comment]
Very nice. 👍

**Pull request merged**
